FROM oven/bun:1.3.14-alpine
RUN addgroup app && adduser -S -G app app
WORKDIR /usr/src/app

COPY package*.json bun.lock ./
COPY packages/client/package.json ./packages/client/
COPY packages/server/package.json ./packages/server/
RUN bun install --frozen-lockfile --ignore-scripts

COPY . .

RUN cd packages/server && bunx prisma generate --schema=./prisma/schema.prisma

# USER app
ENV API_URL=http://localhost:3000/
EXPOSE 5173
ENTRYPOINT  ["bun", "run", "index.ts"]